### ISSUE TITLE
Header Field Addition  : Consent Type

### ISSUE THREAD

**Issue by smartopian** [KantaraInitiative/CISWG#14]
Needs to be defined;
-  is this for explicit, express 
  
  the consent receipt is scoped for explicit types of consent which take an actin by the User and results in a receipt. 

This needs to be defined and the list of consent types for a consent event  needs to be described  @privacyCDN

**Comment by PrivacyCDN** [comment]
Hi;

My proposed draft definitions for the two (2) types of consent for the group to discuss:
1. Implied or Implicit consent where it is reasonable for Bob to assume consent for the collection, use and disclosure of PII for those purposes that a reasonable person associate with the nature of the transaction.
2. Expressed or Explicit where Bob has asked for and received some indication from Alice, unrelated to anything except consent, that provides Bob with consent for the purposes described.

(Note that the phrase is expressed consent - as in the user has expressed their will, NOT express consent - as in this is the speedier solution.)

Supplementary material.

Diagrams

Example 1: Collection of ‘regular’ PII using Implied or Implicit Consent
Example 2: Collection of ‘regular’ PII using Expressed or Explicit Consent
Example 3: Collection of ‘Sensitive’ PII using Implied or Implicit Consent
Example 4: Collection of ‘Sensitive’ PII using Expressed or Explicit Consent

Background

The following was in a prior email:

---

It seems to me that we don’t want to start with a particular standard or guideline, but rather make sure that our end state(s) can be mapped to existing standards and guidelines. If I look at if from the point of view of the PII subject (and assume that the collector is acting in good faith to conform to user/regulatory expectations requirements), then the collector can collect PII in the following ways:

Authority for collection::Type of Consent Required::Method of collection

Required by Law::Consent should NOT be sought, since no is not an option. Notice may or may not be required::As required or necessary to comply
Allowed by Law::Consent should be sought, but only if the collector will honour a do not collect. Notice may or may not be required::As allowed or necessary to fulfill notice.
“Normal” PII::Any consent ((implied | implicit) | (expressed | explicit)). Notice should be provided.::Any method that reasonably allows consent to be implied from actions of user
“Sensitive” PII::Only (expressed | explicit) consent. Notice must be provided::Method must depend on discreet action specifically and only related to consent.

Case 3 above would be the “Alice registers at Bob’s web site with minimum PII for the sole purpose of commenting on the site”. This discussion has allowed me to think this through and articulate it this way. I think that the end state is a record of a PII collection for all 4 of the above cases whether or not consent has been sought. But that’s definitely a parking lot item for after the MVCR which is cases 3 and 4 above, it seems to me.

With a massaging, I think that these four cases can be mapped to existing frameworks. Under the GDPR, implied or implicit consent would fail to meet the standard, but does  map to Canadian principles, GAPP, and 29100. Having a spec that can thus map broadly seems to be the remit we’ve given ourselves. Out of scope, of course, are the cases where the collector is acting in bad faith or outside the bounds of expected privacy norms (i.e. the majority of the the personal data industry).

---

> On Feb 21, 2016, at 13:19, Mark Lizar notifications@github.com wrote:
> 
> Needs to be defined;
> 
> is this for explicit, express
> 
> the consent receipt is scoped for explicit types of consent which take an actin by the User and results in a receipt.
> 
> This needs to be defined and the list of consent types for a consent event needs to be described @privacyCDN https://github.com/privacyCDN
> —
> Reply to this email directly or view it on GitHub https://github.com/KantaraInitiative/CISWG/issues/14.

## 

This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited.

**Comment by smartopian** [comment]
Ok,   added express consent  - expectations being what is measured for implied, but, have separated explicit consent and linked these to the ISO requirements for explicit.  - also, we will need to define specifically the difference between explicit and implied consent in the MVCR conformance (in the future)   - issue closed and being address in action  to #9
