### ISSUE TITLE
Terms Issues: ISO referencing and the term PII 

### ISSUE THREAD

**Issue by smartopian** [KantaraInitiative/CISWG#27]
As I am editing the spec at the moment, I have come across a couple of issues with terms. 

First, as we no longer need to put the spec work forward to a standard development organisation to create a specification standard candidate I think its important to have all terms in the spec so that it is usable without having to reference external documents. 

Second, we have used the term PII as defined in IS0 29100, to refer to the consent grantee, or data subject.  It has occurred to me that the consent grantee doesn’t necessarily have to be identified, to provide both personal data and consent.  As well, we are working on consent centric focus and not necessarily an the basis that all consents require personal identifiable information. 

**The ISO definition is**
"personally identifiable information PII
any information (a) that can be used to identify the person to whom such information pertains, (b) from which such information can be derived, or (c) that is or might be directly or indirectly linked to a natural person.

NOTE To determine whether a PII principal is identifiable, account should be taken of all the means which can reasonably be used by the entity holding the data, or by any other party, to identify that individual. “ 

In this regard, I am wondering if moving to the term personal data would be more appropriate?

**Comment by PrivacyCDN** [comment]
> >  First, as we no longer need to put the spec work forward to a standard development organisation to create a specification standard candidate I think its important to have all terms in the spec so that it is usable without having to reference external documents. 

**​This sounds like re-inventing the wheel. Including standards or definitions by reference simplifies the document, especially if the reference is readily available, which 29100 is. ​**

> > Second, we have used the term PII as defined in IS0 29100, to refer to the consent grantee, or data subject.  It has occurred to me that the consent grantee doesn’t necessarily have to be identified, to provide both personal data and consent.  As well, we are working on consent centric focus and not necessarily an the basis that all consents require personal identifiable information. 
- ​The term _consent grantee_ has not, to my knowledge, been discussed with respect to the consent receipt and is an import from another workgroup. If it has the normative currency of _PII_ as above, then we can discuss whether it should be included by reference as above.​ If it's a new term, or one not used in a generally accepted standard, iIt needs to be discussed before we use it, n'est pas? 
- Secondly, PII refers to the data, not the data subject. 
- Thirdly, in the context of the MVCR I was under the impression that we were building this around the simple two party case, in which case the data subject is implicitly identified as one party to the transaction. More generally, in many if not most use cases the necessity for consent ceases to apply when the data to which consent applies ceases to be personally identifiable information. 

**So it seems to me that while there may be exceptions, the general case is that consents will be linked with PII.**
​

> > The ISO definition is
> > "personally identifiable information PII
> > any information (a) that can be used to identify the person to whom such information pertains, (b) from which such information can be derived, or (c) that is or might be directly or indirectly linked to a natural person.
> > 
> > NOTE To determine whether a PII principal is identifiable, account should be taken of all the means which can reasonably be used by the entity holding the data, or by any other party, to identify that individual. “ 
> > 
> > In this regard, I am wondering if moving to the term personal data would be suffice instead? 

**How would the definition of this new term differ from PII as defined in ISO 29100? And if it doesn't, why add it?​**

**Comment by smartopian** [comment]
Point 1  Yes agree that grantee and grantor should be discussed.   It was more for descriptive and operational use for working with consent, rather than for standard.  I was thinking it could be used to map to PI subject or Data Subject rather than to a standard. 

Point 2 - its the identifiable part, it restricts the interoperability and usability of mvcr for open contexts if its restricted to identified information by persription to ISO terms.   The idea with minimum viable being that it can be used for any consent, not just those by ISO,

**Comment by maryhodder** [comment]
Just adding my email comment here for posterity:

So this has come up in IDESG and in other standards NIST has done, and also with other orgs where we've looked at their documents.

On the one hand, the FTC recognizes PII as a term of art that means something legally and is definable.  On the other hand, IDESG and the other orgs I've seen have taken to calling it:

Personal Information instead of PII (spelled out).  The reason is that they recognize that PII is a term of art for some but not others, and because
depending in context, some personal information becomes identifiable, and out of context or aggregated and collapsed, it's not (so) identifiable.

So they/we wanted users of the documents to have to think about context, think about what may be perceived as personal to the user, and so the definition for now (we are in the midst of a definitions review and expansion for better defs and a few more terms):

"Personal information" broadly means any information about or linked to a user that is collected, used, transmitted, or stored in or by digital identity management functions. 

I think Personal Information is better because it implies context, verses data which is inert without context or use. However, data as the most basic bits, and in some ways we do want to be as basic as that.

However, in the W3C Tracking (DNT) effort, they use this to get at the problem, although do not use PII or PI or user data or anything.. they just say "data":

[quote]  
3.3.1.2 Data Minimization, Retention and Transparency
Data collected by a party for permitted uses must be minimized to the data reasonably necessary for such permitted uses. Such data must not be retained any longer than is proportionate to, and reasonably necessary for, such permitted uses. A party must not rely on unique identifiers if alternative solutions are reasonably available.

A party must publicly describe definite time periods for which data collected for permitted uses are retained. The party may enumerate different retention periods for different permitted uses. Data must not be used for a permitted use once the data retention period for that permitted use has expired. After there are no remaining permitted uses for given data, the data must be deleted or permanently de-identified.

3.3.1.3 No Personalization
A party that collects data for a permitted use must not use that data to alter a specific user's online experience, except as specifically permitted below.  [end quote]

I think their thinking has value because they are a bunch of smart folks wrestling with similar issues.
mary

**Comment by smartopian** [comment]
I like and prefer data, as personal information in the consent receipt context is already implicit, and consent data is all persona.  (IMHO). i.e. personal information for consent is  implicit to context and negates the need to have this term in the first place. Data is much more clean and accurate.  

But, we do want to be highly inter-operable and as personal data is more specific, goes in line with the ISO and IDESG already, I recommend as editor that we use personal information in the v.0.8 spec, with an action item for @KantaraInitiative/ciswg to put interoperability on the agenda post v0.8 spec draft to see if keeping personal information rather than data is warranted.

**Comment by smartopian** [comment]
Some more info on this topic:

‘Personal data’ is defined in Article 2 of the Directive by reference to 
whether information relates to an identified or identifiable 
individual. 
The Directive provides, in Article 3, that it applies only to the 
processing of personal data where the processing is wholly or partly 
by automatic means, or whe
re it is non- automated processing of  personal data which forms part of a ‘filing system
2’ or is intended to form part of a ‘filing system’.
The Directive therefore considers first whether the information 
relates to an identifiable individual and then describes the two different types of processing (processing by automatic means or non-automated processing within a ‘filing system’) which will bring 
information within the scope of the EC Directive.

**Comment by smartopian** [comment]
as well --> NIST Special Publication 800-122 (http://csrc.nist.gov/publications/nistpubs/800-122/sp800-122.pdf)
defines PII as "any information about an individual maintained by an agency, including (1) any information that can be used to distinguish or trace an individual‘s identity, such as name, social security number, date and place of birth, mother‘s maiden name, or biometric records; and (2) any other information that is linked or linkable to an individual, such as medical, educational, financial, and employment information." So, for example, a user's IP address is not classed as PII on its own, but is classified as linked PII (see Section 3.3.3 Under “Identifiability” for more detail) Also see federal judge ruling in the District of New Jersey dismissed on the pleadings a VPPA claim against Viacom on the grounds that device identifiers, cookie IDs, and IP addresses when linked to video titles are not personally identifiable information.

**Comment by smartopian** [comment]
We have gone ahead with PII and PI, although together it is arguable that personal data covers both PII and PI, but since this is not a formal definition, we have addressed this issue and it can be closed
