### ISSUE TITLE
Secondary Purpose and Location of Collection Field 

### ISSUE THREAD

**Issue by smartopian** [KantaraInitiative/CISWG#36]
- The field 'secondary purpose' was renamed with 'consent preference'; 
- the field 'Location of collection' was removed and instead a column for creating a link for all  fields was added, so Location of collection was moved to the Collection Method Link field.

**Comment by smartopian** [comment]
@PrivacyCDN  are you ok with this change any comments?

**Comment by PrivacyCDN** [comment]
Consent preference doesn’t make any sense, where secondary purpose is a
well understood term amongst people that deal with privacy.

Sincerely,
John Wunderlich
@PrivacyCDN

Call: +1 (647) 669-4749
eMail: john@wunderlich.ca

On 12 May 2016 at 07:59, Mark Lizar notifications@github.com wrote:

> @PrivacyCDN https://github.com/PrivacyCDN are you ok with this change
> any comments?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/KantaraInitiative/CISWG/issues/36#issuecomment-218736371

## 

This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited.

**Comment by iainh1** [comment]
I agree with John.

**Comment by smartopian** [comment]
Ok, 

we can change it back.  Although, there is no term or definition called secondary purpose anywhere.  And to a company its a secondary purpose to a person its a preference.   For marking services its preferences, for law, and the spec I would agree with you that keeping it as secondary purpose will make sense to privacy professionals. 

Who i would suppose would also be an audience for this spec.

**Comment by PrivacyCDN** [comment]
​The term that I conflated is “Secondary Uses”, which refers (often in a
clinical setting) uses of the data for which purpose was not specified but
for which there may be legislative or other authority.

My apologies for any confusion this may have given rise to.

That being said I don’t think I’m more confused on what is meant by consent
preference. It seems to me that when Bob identified the purposes for his
collection of Alice’s data there are three possibilities:
1. The collection is required for a purpose specified by law - no consent
   should be sought, since Alice cannot say now.
2. The collection is necessary to the service being provided by Bob.
   Consent must be sought for the purpose(s) identified in the notice, but if
   Alice does not consent, then Bob cannot provide the services - this should
   be clear in the notice.
3. The collection is optional to the service being provided by Bob. Consent
   must be sought for the purpose(s) identified in the notice, and Bob will
   provide the service regardless of whether there is consent for these
   purposes. Again the notice should be clear on this, and the additional
   purposes should each have a separate opt in consent.

But I think all of the above is superfluous for v1. All we need is to set
out that Bob must provide the purposes for which he is collected the data.
The nuances above are, I think, for V2.

Sincerely,
John Wunderlich
@PrivacyCDN

Call: +1 (647) 669-4749
eMail: john@wunderlich.ca

On 12 May 2016 at 16:05, Mark Lizar notifications@github.com wrote:

> Ok,
> 
> we can change it back. Although, there is no term or definition called
> secondary purpose anywhere. And to a company its a secondary purpose to a
> person its a preference. For marking services its preferences, for law, and
> the spec I would agree with you that keeping it as secondary purpose will
> make sense to privacy professionals.
> 
> Who i would suppose would also be an audience for this spec.
> 
> > On 12 May 2016, at 19:47, iainh1 notifications@github.com wrote:
> > 
> > I agree with John.
> > 
> > > On 12 May 2016, at 19:46, John Wunderlich notifications@github.com
> > > wrote:
> > > 
> > > Consent preference doesn’t make any sense, where secondary purpose is a
> > > well understood term amongst people that deal with privacy.
> > > 
> > > Sincerely,
> > > John Wunderlich
> > > @PrivacyCDN
> > > 
> > > Call: +1 (647) 669-4749
> > > eMail: john@wunderlich.ca
> > > 
> > > On 12 May 2016 at 07:59, Mark Lizar notifications@github.com wrote:
> > > 
> > > > @PrivacyCDN https://github.com/PrivacyCDN are you ok with this
> > > > change
> > > > any comments?
> > > > 
> > > > —
> > > > You are receiving this because you were mentioned.
> > > > Reply to this email directly or view it on GitHub
> > > > <
> > > > https://github.com/KantaraInitiative/CISWG/issues/36#issuecomment-218736371
> > > 
> > > ## 
> > > 
> > > This email and any files transmitted with it are confidential and
> > > intended
> > > solely for the use of the individual or entity to whom they are
> > > addressed.
> > > If you have received this email in error please notify the system
> > > manager.
> > > This message contains confidential information and is intended only
> > > for the
> > > individual named. If you are not the named addressee you should not
> > > disseminate, distribute or copy this e-mail. Please notify the sender
> > > immediately by e-mail if you have received this e-mail by mistake and
> > > delete this e-mail from your system. If you are not the intended
> > > recipient
> > > you are notified that disclosing, copying, distributing or taking any
> > > action in reliance on the contents of this information is strictly
> > > prohibited.
> > > —
> > > You are receiving this because you are subscribed to this thread.
> > > Reply to this email directly or view it on GitHub
> > > 
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly or view it on GitHub <
> > > https://github.com/KantaraInitiative/CISWG/issues/36#issuecomment-218850048
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/KantaraInitiative/CISWG/issues/36#issuecomment-218869911

## 

This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited.

**Comment by smartopian** [comment]
After thinking about it, I think you are right and sticking to the term purpose seems more and more appropriate.

**Comment by PrivacyCDN** [comment]
Based on the last comment, can we close this issue?

**Comment by smartopian** [comment]
That we will change purpose preference back to secondary purpose ?  yes, I think we can close this once  spec is updated.

**Comment by smartopian** [comment]
ok,, I see your point John..   although, we dont have a  v.2 anymore, its now Mode 2. - and to get it out of the way for now- (until later) we can make it an  optional field.  in my view  secondary purpose is partly about telling Alice what she can communicate about in the receipt, and partly for machine readable use to withdraw consent for secondary purposes.
