### ISSUE TITLE
Recommend Adding JSON field names back into main body of Spec

### ISSUE THREAD

**Issue by smartopian** [KantaraInitiative/CISWG#41]
For implementation of this specification implementors are most interested in: 

field type, data type, description and even JSON example.

**Comment by iainh1** [comment]
I would contend that at this stage most implementors (i.e. people with money to spend on consent solutions) will be marketers who know they have a big upcoming problem with GDPR. Some of them know it is an opportunity not a problem.

For that audience we primarily need a solid outline of what a consent receipt is, and what they need to do to test it - pretty much all will be deploying from within a CRM system, a marketing automation tool, and a web CMS. In that scenario what we need is a set of fields in an order that makes sense that they can build out, with logical descriptions and associated guidance.

Example, JSON or otherwise would be good too, but not a deal breaker for this audience at this time.

Talk to you later.

Iain

**Comment by smartopian** [comment]
I would disagree and say that lawyers are the ones tasked with GDPR compliance and solutions at this stage.

**Comment by smartopian** [comment]
Either way, we have members in our workgroup, who aim to implement the consent receipt at scale and require  JSON, we dont have marketers apart of the workgroup who are asking for any different. 

For example MYDATA Finland, UMA, IDESG, HEART WG, and these are only the ones I know of.

**Comment by smartopian** [comment]
is their a  good reason why not to include JSON fields in the spec?

**Comment by iainh1** [comment]
No, provided it does not take another several months to sort that out.

As you have said yourself, we needed to get this spec out late last year for optimum communication and development strategy.

**Comment by PrivacyCDN** [comment]
I don't mind including JSON in the appendix as an example of how an
implementer can comply with the standard, but why lock compliance in with
the standard to one (1) particular technology. Doesn't invalidate the the
contents of the consent if it is exchanged in other formats. Locking in a
particular technology is limiting (but providing a JSON example allows
interoperability for those that want/need it.)

The good reason is that my understanding is that this is a standard to
enable organizations to communicate to users in order to meet their own
requirements (compliance, customer sat, or whatever). If all that an entity
wants, or is capable of doing, is to display a web page with the 18 fields,
or a PDF with the same information that is a valid consent receipt.

Sincerely,
John Wunderlich
@PrivacyCDN

Call: +1 (647) 669-4749
eMail: john@wunderlich.ca

On 23 May 2016 at 15:38, Mark Lizar notifications@github.com wrote:

> is their a good reason why not to include JSON fields in the spec?
> 
> > On 23 May 2016, at 20:34, smarthart mark.lizar@gmail.com wrote:
> > 
> > Either way, we have members in our workgroup, who aim to implement the
> > consent receipt at scale and require JSON, we dont have marketers apart of
> > the workgroup who are asking for any different.
> > 
> > For example MYDATA Finland, UMA, IDESG, HEART WG, and these are only the
> > ones I know of.
> > 
> > > On 23 May 2016, at 20:31, smarthart <mark.lizar@gmail.com <mailto:
> > > mark.lizar@gmail.com>> wrote:
> > > 
> > > I would disagree and say that lawyers are the ones tasked with GDPR
> > > compliance and solutions at this stage.
> > > 
> > > > On 23 May 2016, at 20:30, iainh1 <notifications@github.com <mailto:
> > > > notifications@github.com>> wrote:
> > > > 
> > > > I would contend that at this stage most implementors (i.e. people with
> > > > money to spend on consent solutions) will be marketers who know they have a
> > > > big upcoming problem with GDPR. Some of them know it is an opportunity not
> > > > a problem.
> > > > 
> > > > For that audience we primarily need a solid outline of what a consent
> > > > receipt is, and what they need to do to test it - pretty much all will be
> > > > deploying from within a CRM system, a marketing automation tool, and a web
> > > > CMS. In that scenario what we need is a set of fields in an order that
> > > > makes sense that they can build out, with logical descriptions and
> > > > associated guidance.
> > > > 
> > > > Example, JSON or otherwise would be good too, but not a deal breaker
> > > > for this audience at this time.
> > > > 
> > > > Talk to you later.
> > > > 
> > > > Iain
> > > > 
> > > > > On 23 May 2016, at 20:18, Mark Lizar <notifications@github.com
> > > > > <mailto:notifications@github.com>> wrote:
> > > > > 
> > > > > For implementation of this specification implementors are most
> > > > > interested in:
> > > > > 
> > > > > field type, data type, description and even JSON example.
> > > > > 
> > > > > —
> > > > > You are receiving this because you are subscribed to this thread.
> > > > > Reply to this email directly or view it on GitHub <
> > > > > https://github.com/KantaraInitiative/CISWG/issues/41 <
> > > > > https://github.com/KantaraInitiative/CISWG/issues/41>>
> > > > 
> > > > —
> > > > You are receiving this because you authored the thread.
> > > > Reply to this email directly or view it on GitHub <
> > > > https://github.com/KantaraInitiative/CISWG/issues/41#issuecomment-221069705
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/KantaraInitiative/CISWG/issues/41#issuecomment-221073010

## 

This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited.

**Comment by smartopian** [comment]
Using JSON can be optional or suggested, but, for the spec to be machine readable it should be required to be in the main body of the spec.  Or, how will it be machine readable?

**Comment by xmlgrrl** [comment]
I'm confused as to why "lock-in to one technology" is a bug rather than a feature, as long as it's a level playing field that increases format interoperability. A big benefit of consistently formatted consent receipts (at least, for a lot of my use cases) is being able to aggregate them, do analytics over them, do workflows with them (IFTTT/Zapier), etc. Otherwise you're forced to screen-scrape the content inside the fields. If there is demand for alternate formats beyond JSON for such use cases, create additional language bindings.

**Comment by smartopian** [comment]
I agree Eve, doesnt make sense to make specification for a standard without standardising the machine readable side of it.

**Comment by PrivacyCDN** [comment]
If, as I understand it, the fundamental problem that the consent receipt addresses is that the user is not presented with an opportunity to have a record of the consent then this can be accomplished by multiple methods - including but not restricted to a web pop-up, a pdf and so on. So if someone wants to write a simple wordpress plug-in that provides the necessary information on the screen for the user, I see that as a plus. 
In addition regulators are adamantly technology neutral, and as policy wonks are more likely to buy into the notion of a receipt that is also technology neutral.
On the basis of the above, then the development of an interoperable electronic reciept becomes the next step.   
Get Outlook for iOS

On Mon, May 23, 2016 at 1:07 PM -0700, "Eve Maler" notifications@github.com wrote:

I'm confused as to why "lock-in to one technology" is a bug rather than a feature, as long as it's a level playing field that increases format interoperability. A big benefit of consistently formatted consent receipts (at least, for a lot of my use cases) is being able to aggregate them, do analytics over them, do workflows with them (IFTTT/Zapier), etc. Otherwise you're forced to screen-scrape the content inside the fields. If there is demand for alternate formats beyond JSON for such use cases, create additional language bindings.

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub

## 

This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited.

**Comment by smartopian** [comment]
The way I see it, there are multiple parties with use cases that require interoperability both in and out of the workgroup, and that if someone wants to put a consent receipt in a non machine readable format, it doesnt need to have data field names or types.

I have yet to see one valid use case, client or website to say otherwise. 
- Mark

**Comment by iainh1** [comment]
Agreed. But we do include the JSON fields in the spec as ‘optional’; so those that wish to push ahead with that can do. If other methods fall by the way side over time then that would seem fine; and if they don’t that also tells its own story.

Iain

**Comment by xmlgrrl** [comment]
I don't see the value of what RFC 2119 would call "MAY" assertions. They don't give you interoperability, so why include them? What is the exact contention about including normative ("MUST") testable assertions in the spec? Is it about what language to encode the field boundaries in, e.g. JSON vs. something else?

**Comment by iainh1** [comment]
The very obvious use case that does not require machine readable receipts is the many large organisations who would see inter-operability for what it is - a way to weaken their hold.

That’s why interoperability is a good thing for the end user, and why it should absolutely be in our v 2. But having it in up front as mandatory rather than optional, in my view. will impact adoption in the large organisation space.

Iain

**Comment by xmlgrrl** [comment]
Interoperability is also a good thing for organizations, of which there are an increasing number, that seek to innovate around identity and access for end users. I submit that V1 vs. V2 makes no difference to the rationale you've provided, and that my use cases give a rationale for standardizing syntax sooner rather than later. If "MAY" really means "MUST", why not say so?

**Comment by smartopian** [comment]
Today from the MYdata Harri wrote an email saying 

" Regarding the maturity and release plan of the machine-readable format of MVCR, we’d like to understand in the MyData engineering team when a sufficiently stable JSON specification release is due. This as we don’t yet know if we could release our MyData SDK in late August with the consent receipt baked in or not. For the time being, we’re holding a place for it, but will need to know by early June.”

**Comment by PrivacyCDN** [comment]
Eve;
For me it boils down to interoperability of information first (what info Alice gets) then interoperability of syntax (how Alice's machine agent/s can talk to each other). 

Get Outlook for iOS

On Mon, May 23, 2016 at 3:12 PM -0700, "Eve Maler" notifications@github.com wrote:

Interoperability is also a good thing for organizations, of which there are an increasing number, that seek to innovate around identity and access for end users. I submit that V1 vs. V2 makes no difference to the rationale you've provided, and that my use cases give a rationale for standardizing syntax sooner rather than later. If "MAY" really means "MUST", why not say so?

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub

## 

This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited.

**Comment by smartopian** [comment]
Still not a reason for not making JSON a must.

**Comment by iainh1** [comment]
That excludes the many organisations who might see the logic in consent receipts, but who cannot or do not wish to deliver them in JSON format.

The case for mandatory technical format has not been made as yet in my view; at least not in such a way as to demonstrate how those unwilling or unable to work in that format would not therefore be excluded.

Iain

**Comment by smartopian** [comment]
Hi Iain, 

Can you give one example?  Is there any use case from any stakeholder for not making this a JSON spec?

**Comment by smartopian** [comment]
Just to add to that, the entire country of Finland wants to make it mandatory and JSON based.

**Comment by PrivacyCDN** [comment]
Again, the use case of an add-in or a module for WordPress, Joomla or
Drupal that, at installation, gets Bob's basic information and the, at run
time, provides a simple pop up screen for Alice which she can choose to
orint or not.

It may or may not provide an electronic version but it accomolishes the
basic task of informing Alice in a way that she can hold Bob to account.

On May 23, 2016 at 6:33:41 PM, Mark Lizar (notifications@github.com) wrote:

> Hi Iain,
> 
> Can you give one example? Is there any use case from any stakeholder for
> not making this a JSON spec?
> 
> > On 23 May 2016, at 23:30, iainh1 notifications@github.com wrote:
> > 
> > That excludes the many organisations who might see the logic in consent
> > receipts, but who cannot or do not wish to deliver them in JSON format.
> > 
> > The case for mandatory technical format has not been made as yet in my
> > view; at least not in such a way as to demonstrate how those unwilling or
> > unable to work in that format would not therefore be excluded.
> > 
> > Iain
> > 
> > > On 23 May 2016, at 23:24, Mark Lizar notifications@github.com wrote:
> > > 
> > > Still not a reason for not making JSON a must.
> > > 
> > > > On 23 May 2016, at 23:19, John Wunderlich notifications@github.com
> > > > wrote:
> > > > 
> > > > Eve;
> > > > For me it boils down to interoperability of information first (what
> > > > info Alice gets) then interoperability of syntax (how Alice's machine
> > > > agent/s can talk to each other).
> > > > 
> > > > Get Outlook for iOS
> > > > 
> > > > On Mon, May 23, 2016 at 3:12 PM -0700, "Eve Maler" <
> > > > notifications@github.com> wrote:
> > > > 
> > > > Interoperability is also a good thing for organizations, of which
> > > > there are an increasing number, that seek to innovate around identity and
> > > > access for end users. I submit that V1 vs. V2 makes no difference to the
> > > > rationale you've provided, and that my use cases give a rationale for
> > > > standardizing syntax sooner rather than later. If "MAY" really means
> > > > "MUST", why not say so?
> > > > 
> > > > —
> > > > You are receiving this because you were mentioned.
> > > > Reply to this email directly or view it on GitHub
> > > > 
> > > > ## 
> > > > 
> > > > This email and any files transmitted with it are confidential and
> > > > intended
> > > > solely for the use of the individual or entity to whom they are
> > > > addressed.
> > > > If you have received this email in error please notify the system
> > > > manager.
> > > > This message contains confidential information and is intended only
> > > > for the
> > > > individual named. If you are not the named addressee you should not
> > > > disseminate, distribute or copy this e-mail. Please notify the sender
> > > > immediately by e-mail if you have received this e-mail by mistake and
> > > > delete this e-mail from your system. If you are not the intended
> > > > recipient
> > > > you are notified that disclosing, copying, distributing or taking any
> > > > action in reliance on the contents of this information is strictly
> > > > prohibited.
> > > > —
> > > > You are receiving this because you authored the thread.
> > > > Reply to this email directly or view it on GitHub <
> > > > https://github.com/KantaraInitiative/CISWG/issues/41#issuecomment-221113171
> > > 
> > > —
> > > You are receiving this because you commented.
> > > Reply to this email directly or view it on GitHub
> > > 
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly or view it on GitHub <
> > > https://github.com/KantaraInitiative/CISWG/issues/41#issuecomment-221115437
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/KantaraInitiative/CISWG/issues/41#issuecomment-221116137

## 

This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited.

**Comment by PrivacyCDN** [comment]
There is nothing to prevent that for Finland in the simple version.

On May 23, 2016 at 6:36:00 PM, Mark Lizar (notifications@github.com) wrote:

> Just to add to that, the entire country of Finland wants to make it
> mandatory and JSON based.
> 
> > On 23 May 2016, at 23:33, smarthart mark.lizar@gmail.com wrote:
> > 
> > Hi Iain,
> > 
> > Can you give one example? Is there any use case from any stakeholder for
> > not making this a JSON spec?
> > 
> > > On 23 May 2016, at 23:30, iainh1 <notifications@github.com <mailto:
> > > notifications@github.com>> wrote:
> > > 
> > > That excludes the many organisations who might see the logic in consent
> > > receipts, but who cannot or do not wish to deliver them in JSON format.
> > > 
> > > The case for mandatory technical format has not been made as yet in my
> > > view; at least not in such a way as to demonstrate how those unwilling or
> > > unable to work in that format would not therefore be excluded.
> > > 
> > > Iain
> > > 
> > > > On 23 May 2016, at 23:24, Mark Lizar <notifications@github.com
> > > > <mailto:notifications@github.com>> wrote:
> > > > 
> > > > Still not a reason for not making JSON a must.
> > > > 
> > > > > On 23 May 2016, at 23:19, John Wunderlich <notifications@github.com
> > > > > <mailto:notifications@github.com>> wrote:
> > > > > 
> > > > > Eve;
> > > > > For me it boils down to interoperability of information first (what
> > > > > info Alice gets) then interoperability of syntax (how Alice's machine
> > > > > agent/s can talk to each other).
> > > > > 
> > > > > Get Outlook for iOS
> > > > > 
> > > > > On Mon, May 23, 2016 at 3:12 PM -0700, "Eve Maler" <
> > > > > notifications@github.com mailto:notifications@github.com> wrote:
> > > > > 
> > > > > Interoperability is also a good thing for organizations, of which
> > > > > there are an increasing number, that seek to innovate around identity and
> > > > > access for end users. I submit that V1 vs. V2 makes no difference to the
> > > > > rationale you've provided, and that my use cases give a rationale for
> > > > > standardizing syntax sooner rather than later. If "MAY" really means
> > > > > "MUST", why not say so?
> > > > > 
> > > > > —
> > > > > You are receiving this because you were mentioned.
> > > > > Reply to this email directly or view it on GitHub
> > > > > 
> > > > > ## 
> > > > > 
> > > > > This email and any files transmitted with it are confidential and
> > > > > intended
> > > > > solely for the use of the individual or entity to whom they are
> > > > > addressed.
> > > > > If you have received this email in error please notify the system
> > > > > manager.
> > > > > This message contains confidential information and is intended only
> > > > > for the
> > > > > individual named. If you are not the named addressee you should not
> > > > > disseminate, distribute or copy this e-mail. Please notify the
> > > > > sender
> > > > > immediately by e-mail if you have received this e-mail by mistake
> > > > > and
> > > > > delete this e-mail from your system. If you are not the intended
> > > > > recipient
> > > > > you are notified that disclosing, copying, distributing or taking
> > > > > any
> > > > > action in reliance on the contents of this information is strictly
> > > > > prohibited.
> > > > > —
> > > > > You are receiving this because you authored the thread.
> > > > > Reply to this email directly or view it on GitHub <
> > > > > https://github.com/KantaraInitiative/CISWG/issues/41#issuecomment-221113171
> > > > > <
> > > > > https://github.com/KantaraInitiative/CISWG/issues/41#issuecomment-221113171
> > > > 
> > > > —
> > > > You are receiving this because you commented.
> > > > Reply to this email directly or view it on GitHub
> > > > 
> > > > —
> > > > You are receiving this because you authored the thread.
> > > > Reply to this email directly or view it on GitHub <
> > > > https://github.com/KantaraInitiative/CISWG/issues/41#issuecomment-221115437
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/KantaraInitiative/CISWG/issues/41#issuecomment-221116573

## 

This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited.

**Comment by smartopian** [comment]
And why cant this be JSON?   BTW - Finland wont be using it if its not in stable JSON. , I think the point is they will make their own.

**Comment by PrivacyCDN** [comment]
Presumably the JSON appendix will be stable JSON.  

Get Outlook for iOS

On Mon, May 23, 2016 at 4:11 PM -0700, "Mark Lizar" notifications@github.com wrote:

And why cant this be JSON?   BTW - Finland wont be using it if its not in stable JSON. , I think the point is they will make their own. 

> On 24 May 2016, at 00:06, John Wunderlich notifications@github.com wrote:
> 
> Again, the use case of an add-in or a module for WordPress, Joomla or
> 
> Drupal that, at installation, gets Bob's basic information and the, at run
> 
> time, provides a simple pop up screen for Alice which she can choose to
> 
> orint or not.
> 
> It may or may not provide an electronic version but it accomolishes the
> 
> basic task of informing Alice in a way that she can hold Bob to account.
> 
> On May 23, 2016 at 6:33:41 PM, Mark Lizar (notifications@github.com) wrote:
> 
> > Hi Iain,
> > 
> > Can you give one example? Is there any use case from any stakeholder for
> > 
> > not making this a JSON spec?
> > 
> > > On 23 May 2016, at 23:30, iainh1 notifications@github.com wrote:
> > > 
> > > That excludes the many organisations who might see the logic in consent
> > 
> > receipts, but who cannot or do not wish to deliver them in JSON format.
> > 
> > > The case for mandatory technical format has not been made as yet in my
> > 
> > view; at least not in such a way as to demonstrate how those unwilling or
> > 
> > unable to work in that format would not therefore be excluded.
> > 
> > > Iain
> > > 
> > > > On 23 May 2016, at 23:24, Mark Lizar notifications@github.com wrote:
> > > > 
> > > > Still not a reason for not making JSON a must.
> > > > 
> > > > > On 23 May 2016, at 23:19, John Wunderlich notifications@github.com
> > 
> > wrote:
> > 
> > > > > Eve;
> > > > > 
> > > > > For me it boils down to interoperability of information first (what
> > 
> > info Alice gets) then interoperability of syntax (how Alice's machine
> > 
> > agent/s can talk to each other).
> > 
> > > > > Get Outlook for iOS
> > > > > 
> > > > > On Mon, May 23, 2016 at 3:12 PM -0700, "Eve Maler" <
> > 
> > notifications@github.com> wrote:
> > 
> > > > > Interoperability is also a good thing for organizations, of which
> > 
> > there are an increasing number, that seek to innovate around identity and
> > 
> > access for end users. I submit that V1 vs. V2 makes no difference to the
> > 
> > rationale you've provided, and that my use cases give a rationale for
> > 
> > standardizing syntax sooner rather than later. If "MAY" really means
> > 
> > "MUST", why not say so?
> > 
> > > > > —
> > > > > 
> > > > > You are receiving this because you were mentioned.
> > > > > 
> > > > > Reply to this email directly or view it on GitHub
> > > > > 
> > > > > ## 
> > > > > 
> > > > > This email and any files transmitted with it are confidential and
> > 
> > intended
> > 
> > > > > solely for the use of the individual or entity to whom they are
> > 
> > addressed.
> > 
> > > > > If you have received this email in error please notify the system
> > 
> > manager.
> > 
> > > > > This message contains confidential information and is intended only
> > 
> > for the
> > 
> > > > > individual named. If you are not the named addressee you should not
> > > > > 
> > > > > disseminate, distribute or copy this e-mail. Please notify the sender
> > > > > 
> > > > > immediately by e-mail if you have received this e-mail by mistake and
> > > > > 
> > > > > delete this e-mail from your system. If you are not the intended
> > 
> > recipient
> > 
> > > > > you are notified that disclosing, copying, distributing or taking any
> > > > > 
> > > > > action in reliance on the contents of this information is strictly
> > > > > 
> > > > > prohibited.
> > > > > 
> > > > > —
> > > > > 
> > > > > You are receiving this because you authored the thread.
> > > > > 
> > > > > Reply to this email directly or view it on GitHub <
> > 
> > https://github.com/KantaraInitiative/CISWG/issues/41#issuecomment-221113171
> > 
> > > > —
> > > > 
> > > > You are receiving this because you commented.
> > > > 
> > > > Reply to this email directly or view it on GitHub
> > > 
> > > —
> > > 
> > > You are receiving this because you authored the thread.
> > > 
> > > Reply to this email directly or view it on GitHub <
> > 
> > https://github.com/KantaraInitiative/CISWG/issues/41#issuecomment-221115437
> > 
> > 
> > —
> > 
> > You are receiving this because you were mentioned.
> > 
> > Reply to this email directly or view it on GitHub
> > 
> > https://github.com/KantaraInitiative/CISWG/issues/41#issuecomment-221116137
> 
> ## 
> 
> This email and any files transmitted with it are confidential and intended 
> 
> solely for the use of the individual or entity to whom they are addressed. 
> 
> If you have received this email in error please notify the system manager. 
> 
> This message contains confidential information and is intended only for the 
> 
> individual named. If you are not the named addressee you should not 
> 
> disseminate, distribute or copy this e-mail. Please notify the sender 
> 
> immediately by e-mail if you have received this e-mail by mistake and 
> 
> delete this e-mail from your system. If you are not the intended recipient 
> 
> you are notified that disclosing, copying, distributing or taking any 
> 
> action in reliance on the contents of this information is strictly 
> 
> prohibited.
> 
> —
> 
> You are receiving this because you authored the thread.
> 
> Reply to this email directly or view it on GitHub https://github.com/KantaraInitiative/CISWG/issues/41#issuecomment-221122091

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub

## 

This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited.

**Comment by smartopian** [comment]
John, 

What you describe is an idealistic policy document with a technical appendix, What has always been proposed is a technical specification for mapping legal requirements designed for Alice based on ISO 29100; 

Presumably, the appendix will be  redundant if the data fields and types are in the table, and the stipulation is made that the spec is confromant if any format if its not machine readable, JSON is not required. (thats one sentence ) . 

I recommend a WG vote 

 Putting it in the appendix just makes it more complicated, less usable, delays the work and undermines all the work done so far and the people in the WG that are waiting for it.  In fact, we had this pretty much done after Justin did the JSON work.   Its been taking it out of JSON which has delayed this for so long.  

Not only is this delay8ing this incredibly, but, without a technical format to conform to I suspect we will loose most of the support that the hard volunteer work has developed and that this spec has gained. 

Lastly - creating a policy specification (pretending to be a technical specification) is not a route to creating usable policy.

**Comment by PrivacyCDN** [comment]
In the last exchange of off line emails there appeared to be the possibility  of consensus on the following:

The v 1 Kantara standard consent receipt will set out a JSON definition of the contents of a v 1 version of a consent receipt. The standard will say that IF the implementor of a consent receipt wants or needs to use JSON, then they MUST use JSON as defined in the standard for the result to be a Kantara compliant version of the receipt.

If this is correct, can we close this issue?

**Comment by iainh1** [comment]
In my view, yes we could.

**Comment by smartopian** [comment]
In terms of conforming to spec for JSON,  I think there is a call to vote on the fields being a must and having JSON in the spec not in the appendix. 

so this cant be closed as many in the WG are waiting for authoritative JSON spec to implement against.  So we would need to run this by the list.

**Comment by smartopian** [comment]
this was voted on and resolved.
