### ISSUE TITLE
Purpose Field Query: Is it purpose category or purpose 

### ISSUE THREAD

**Issue by smartopian** [KantaraInitiative/CISWG#43]
So, in the v.0.7 implementation and CRG, we have purpose category, not purpose..   

So -- a purpose listing would  be  | service name | purpose category (from the list) | PI category |  etc. 

Like in our example at http://api.consentreceipt.org/

But, we have just purpose in current list, can we clarify understanding on this?  change this to purpose categories?

**Comment by PrivacyCDN** [comment]
The api as it is presented in the api [documentation](http://api.consentreceipt.org/) uses the field name purpose, and contains multiple elements. The use of the phrase purpose categories obfuscates, in my view, what is simply a list of purposes. The API documentation contains a number of other examples where the single field name contains multiple elements (see ‘sharing’ or ‘data-controller’).  What I proposed on the call the other day for purpose is kinda matching what is already in the JSON api. Where there is a JSON object that contains multiple entries, that implies a table or listing in the receipt and vice
versa. Where Bob is a simple site his purposes and uses are presumably stable and a standard table or listing gives Alice the necessary information. Where Bob is larger or more sophisticate or anticipates
changing purposes and uses having this as data is valuable. See below.

Currently the JSON API field ‘purpose' is an array of a series of pairs involving “Naming the Service” and “Stating the Active Purpose”. This is quite close to what I said proposed on the call. If you turn the api into a table you get with a series of entries like this:

| Name of Service | Purpose |
| Name of Service | Purpose |

The API Documentation used the following examples

Bob’s store: delivery
or
DISWG Membership: Join

What I proposed turns out notionally to be adding a column or columns to the existing table described in the API documentation, depending on how we want to parse it. We inverse the order of the initial two fields, and then add one or more to qualify it, thus something like the following might be valid

Purpose for collection : Use for identified purpose : Use is part of basic
service (y/n): Condition for termination (i.e. information can no longer be
used or disclosed for this purpose and should be deleted where it exists
solely for this purpose)

Which could lead to an entry like this

Attribute user comments: Create and maintain user credentials: N (only
necessary to make comments, not view web site): User initiation
Market services to user: Send marketing emails: N: User initiation
…and so on

This could mean multiple lines like:

Purpose 1: Use 1: Y : termination of user
Purpose 1: Use 2: Y : Six years from last interaction with user
Purpose 1: Use 3: N : User initiated
Purpose 2: Use 3: N : User initiated
Purpose 2: Use 4: N : User initiated
Purpose 2: Use 5: N : User initiated

Which provides ample opportunity for automating a range of user/consent
management issues.

**Comment by PrivacyCDN** [comment]
Can issue #42 and #43 be merged? They appear to be on the same topic and I suspect a resolution of one will resolve both.

**Comment by maryhodder** [comment]
Resolved: we are using purpose category in field table.
