### ISSUE TITLE
Recommend public Key for JWT Token in Consent Receipt, 

### ISSUE THREAD

**Issue by smartopian** [KantaraInitiative/CISWG#44]
While working through implementation when a consent receipt is provided by email in JWT, it needs the public key to be viewable, recommend adding field for public key for JSON, as well as perhaps a link to a JWT viewer to view receipts once emailed.

**Comment by PrivacyCDN** [comment]
Need a more fulsome explanation 

John Wunderlich,

Sent frum a mobile device,
Pleez 4give speling erurz

"...a world of near-total surveillance and endless record-keeping is likely to be one with less liberty, less experimentation, and certainly far less joy..." A. Michael Froomkin

On Wed, May 25, 2016 at 1:57 PM -0700, "Mark Lizar" notifications@github.com wrote:

While working through implementation when a consent receipt is provided by email in JWT, it needs the public key to be viewable, recommend adding field for public key for JSON, as well as perhaps a link to a JWT viewer to view receipts once emailed. 

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub

## 

This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited.

**Comment by smartopian** [comment]
If the receipt is not JSON, and in a encrypted web token  with a public key, then it should not be emailed as it would be in plain text as this would be leak private consent information in plain text across the internet. 

THe

**Comment by dturnerx** [comment]
Done DRAFT 5 https://kantarainitiative.org/confluence/download/attachments/76447870/Consent%20Receipt%20Specification%201_1_0%20DRAFT%205a.docx?version=1&modificationDate=1508987029000&api=v2
