### ISSUE TITLE
Suggest creating a wiki page orGithub page that is linked directly from consent receipts to explain CR to end users

### ISSUE THREAD

**Issue by smartopian** [KantaraInitiative/CISWG#45]
should we create such a page ? 

should this be on github or on the wiki?

**Comment by PrivacyCDN** [comment]
Am explanation of the standard - might be doable to extend whatever guidance is in the standard. An explanation of consent? Too big and too many differences in the team to make this an easy proposition to say no to;-)

John Wunderlich,

Sent frum a mobile device,
Pleez 4give speling erurz

"...a world of near-total surveillance and endless record-keeping is likely to be one with less liberty, less experimentation, and certainly far less joy..." A. Michael Froomkin

On Wed, May 25, 2016 at 2:02 PM -0700, "Mark Lizar" notifications@github.com wrote:

should we create such a page ? 

should this be on github or on the wiki? 

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub

## 

This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited.

**Comment by smartopian** [comment]
Perhaps this topic is an appropriate place to discuss differences rather than loading differences into spec talk about the english label for a standard JSON field. As the topic of the eng label has not moved forward in months, it appears that its the other issues that are getting in the way.     It seems we should separate some issues into legal /technical/marketing information for different audiences as well.

So perhaps, two wiki pages, one for end users, one for the audiences.
