### ISSUE TITLE
Changing (or better defining) Sharing - Rather than change sharing to disclosure

### ISSUE THREAD

**Issue by smartopian** [KantaraInitiative/CISWG#48]
So --> while  I think Sharing may not  be well defined and has a connotation that means people intend to do something.  
IN this specification the connotation is that people get a notice and provide explicit consent to share personal information. 
In law - if you look at the definition, the term clearly means - for companies to disclose information about people to third parties. 
-- This is clearly visable if you look at the GDPR and search for the word disclosure.  
-- Sharing -- in this specification means - I explicitly consent to sharing this type of information wiht you for this purpose. 
- The name of the work group, is consent and information sharing, where we created an effort to make a consent standard for people to share more valuable information in a trusted way .  Consent is not possible without notice, this has evolved from 2005 - http://wiki.idcommons.net/Identity_Trust_Charter) 
  so, if you read the charter, the aim is to create a standard for consent and information sharing that conforms to ISO 29100.   Which started with a project called open notice. (this evolved into consent receipts)  -   The ultimate aim, is to create a standard that enables people to share their information in meaningful and trusted ways.   --  tracking disclosures, is perhaps a use case the consent receipt can use.

**Comment by maryhodder** [comment]
On the call on Thursday the group agreed:

AGREEMENT: we agreed that for Guidance under the Field Table, language would be as follows:

For the end-user: we will use "Sharing" to describe, in a Field name, when the end-user shares with the PII Controller. However, for information we direct in the spec to the implementer (PII Controller) we will use terms that are more precise such as "disclosure" and "use" and "collection".

Therefore guidance for the Implementer for Field name: SHARING Y/N should read, "Disclosure of PII data MUST be able to be turned on and off with a Yes or No choice. This a yes / no flag provided as a notice to the end-user (PII subject) that some data, which may be sensitive, is being collected by the PII Controller, and can be disclosed to other parties, so that the PI Subject may take steps to safeguard their data. It indicates that there are policies out of band of the receipt which should be present."  

And for Field Name: 3RD PARTY DISCLOSURE Y/N should read, "Disclosure of PII data with 3rd parties SHOULD be able to be turned on and off with a Yes or No choice. This a yes / no flag provided as a notice to the user that some data, which may be sensitive, is being collected, so that the PI Subject may take steps to safeguard their data. It indicates that there are policies out of band of the receipt which should be present."
