### ISSUE TITLE
Sensitive PII Category list and guidance in Field table -- how will this work?

### ISSUE THREAD

**Issue by maryhodder** [KantaraInitiative/CISWG#50]
Sensitive PII Category list and guidance in Field table -- how will this work?

**Comment by PrivacyCDN** [comment]
List should be in guidance?

John Wunderlich,

Sent frum a mobile device,
Pleez 4give speling erurz

"...a world of near-total surveillance and endless record-keeping is likely to be one with less liberty, less experimentation, and certainly far less joy..." A. Michael Froomkin

On Sat, Jun 25, 2016 at 12:20 PM -0400, "maryhodder" notifications@github.com wrote:

Sensitive PII Category list and guidance in Field table -- how will this work?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.

## 

This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited.

**Comment by smartopian** [comment]
In v0.7 - Its a drop down list of categories (like the other list of categories) which, most importantly, has an other field - so that organisations can add their own.  I recommend  putting into Appendix with the other drop down lists, and just having SPII  or Sensitive Personally Identified Information as a term in the glossary . 

Sensitive data often has jurisdiction, industry and context specific requirements for notice and consent, which is out of scope of this version of consent specification, but a primary reason why the consent receipt is in demand.   I

I think sensitive data use case comes under the  ISO 29100 use case. Where Explicit Consent is achieved under the control of the PII Principal of Sensitive Personally Identifiable Information  to be discosed or transferred through an intermediary (or to another 3rd Party.) see section 8.3 of the ISO 29100 framework section Empower Control for the PII Principal. 

Our tasks is to just show   the consent receipt can be used to capture consent to share SPII.  (not define what is SPII) and that this can be used (but out of scope) by the user in the future. 

In the Appendix perhaps we should add some text like: 

" The consent receipt can be used to list sensitive data  purpose, and policy.  Sensitive data categories, like the categories listed here, have additional consent notice and requirements that are specific to the type of sensitive data, and the  jurisdiction.  As a result guidance for the use of sensitive data categories is out of scope of this document. "

**Comment by smartopian** [comment]
Ok.. So, it took a while, but  I think I have figured out how SPI fits into the spec for the moment.  Please take a look at the Considerations section -  Have moved the considerations into th supplemental guidance and moved the SPI stuff into a consideration called: SPI: Liability & Compliance

Also, for the moment,  I have crammed SPI categories  into item 16 in Appendix A; PI Categories    (and deleted the extra appendix item)
