### ISSUE TITLE
Unique numbers for consent receipt as requirement

### ISSUE THREAD

**Issue by maryhodder** [KantaraInitiative/CISWG#51]
1. Should we have a unique number for each consent receipt as a requirement?
   What is the benefit of this? And the potential harms?

AGREEMENT: The group agrees to use a UUID for Mode 2 for machine readable, and an internally assigned # to a receipt for Mode 1.

Agreement made in the group last Thursday.

**Comment by maryhodder** [comment]
Agreement made in the group last Thursday.

**Comment by PrivacyCDN** [comment]
Internally assigned and unique to the issuer. I.e, for mode 1 the receipt ID or receipt # can be a simple serial number.  

John Wunderlich,

Sent frum a mobile device,
Pleez 4give speling erurz

"...a world of near-total surveillance and endless record-keeping is likely to be one with less liberty, less experimentation, and certainly far less joy..." A. Michael Froomkin

On Sat, Jun 25, 2016 at 12:33 PM -0400, "maryhodder" notifications@github.com wrote:

Should we have a unique number for each consent receipt as a requirement?
What is the benefit of this? And the potential harms?

AGREEMENT: The group agrees to use a UUID for Mode 2 for machine readable, and an internally assigned # to a receipt for Mode 1.

Agreement made in the group last Thursday.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.

## 

This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited.
