### ISSUE TITLE
Consent Notices? Are these receipts? Can we back out of "notices" as a descriptor for a receipt?

### ISSUE THREAD

**Issue by maryhodder** [KantaraInitiative/CISWG#54]
AGREEMENT: all receipts are receipts, but Mode 1 and Mode 2 can also be referred interchangeably with "Human Readable" for Mode 1 and "Machine Readable" for Mode 2. Also if we get to a Mode 3 we can refer possibly to those as "Interoperable" -- but that 3rd version is TBD.

**Comment by maryhodder** [comment]
Agreement made in Last Thursday's meeting.

**Comment by iainh1** [comment]
Isn't mode 2 also machine readable? So mode 1 could be human readable only?

**Comment by PrivacyCDN** [comment]
I think Mode 2, by virtue of using a tech spec may already be interoperable. I think of mode 3 as 'dynamic' - instead of being a point in time reference to a single consent event it becomes a 'living document' that is always up to date. At least that's my view of the end state to be worked towards.m
John Wunderlich,

Sent frum a mobile device,
Pleez 4give speling erurz

"...a world of near-total surveillance and endless record-keeping is likely to be one with less liberty, less experimentation, and certainly far less joy..." A. Michael Froomkin

On Sat, Jun 25, 2016 at 12:35 PM -0400, "maryhodder" notifications@github.com wrote:

AGREEMENT: all receipts are receipts, but Mode 1 and Mode 2 can also be referred interchangeably with "Human Readable" for Mode 1 and "Machine Readable" for Mode 2. Also if we get to a Mode 3 we can refer possibly to those as "Interoperable" -- but that 3rd version is TBD.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.

## 

This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited.

**Comment by maryhodder** [comment]
Agree in a way.. happy to call it "dynamic" but when I hear interoperable i
actually think "full duplex".. as in I can select something on, in our
case, the Receipt, and messaging goes back and change happens due to my
selection.

So.. interoperable, or dynamic.. either way. But for me.. what I'd like to
see in Mode 3 is Full Duplex. But that's a nerdy geek term.. so not for
public consumption probably.

mary

**Comment by PrivacyCDN** [comment]
Thinking aligned, terminology needs work. But parking lot for now

John Wunderlich,

Sent frum a mobile device,
Pleez 4give speling erurz

"...a world of near-total surveillance and endless record-keeping is likely to be one with less liberty, less experimentation, and certainly far less joy..." A. Michael Froomkin

On Sat, Jun 25, 2016 at 8:55 PM -0400, "maryhodder" notifications@github.com wrote:

Agree in a way.. happy to call it "dynamic" but when I hear interoperable i

actually think "full duplex".. as in I can select something on, in our

case, the Receipt, and messaging goes back and change happens due to my

selection.

So.. interoperable, or dynamic.. either way. But for me.. what I'd like to

see in Mode 3 is Full Duplex. But that's a nerdy geek term.. so not for

public consumption probably.

mary

On Sat, Jun 25, 2016 at 12:02 PM, John Wunderlich notifications@github.com

wrote:

> I think Mode 2, by virtue of using a tech spec may already be
> 
> interoperable. I think of mode 3 as 'dynamic' - instead of being a point in
> 
> time reference to a single consent event it becomes a 'living document'
> 
> that is always up to date. At least that's my view of the end state to be
> 
> worked towards.m
> 
> John Wunderlich,
> 
> Sent frum a mobile device,
> 
> Pleez 4give speling erurz
> 
> "...a world of near-total surveillance and endless record-keeping is
> 
> likely to be one with less liberty, less experimentation, and certainly far
> 
> less joy..." A. Michael Froomkin
> 
> On Sat, Jun 25, 2016 at 12:35 PM -0400, "maryhodder" <
> 
> notifications@github.com> wrote:
> 
> AGREEMENT: all receipts are receipts, but Mode 1 and Mode 2 can also be
> 
> referred interchangeably with "Human Readable" for Mode 1 and "Machine
> 
> Readable" for Mode 2. Also if we get to a Mode 3 we can refer possibly to
> 
> those as "Interoperable" -- but that 3rd version is TBD.
> 
> —
> 
> You are receiving this because you are subscribed to this thread.
> 
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> ## 
> 
> This email and any files transmitted with it are confidential and intended
> 
> solely for the use of the individual or entity to whom they are addressed.
> 
> If you have received this email in error please notify the system manager.
> 
> This message contains confidential information and is intended only for
> 
> the
> 
> individual named. If you are not the named addressee you should not
> 
> disseminate, distribute or copy this e-mail. Please notify the sender
> 
> immediately by e-mail if you have received this e-mail by mistake and
> 
> delete this e-mail from your system. If you are not the intended recipient
> 
> you are notified that disclosing, copying, distributing or taking any
> 
> action in reliance on the contents of this information is strictly
> 
> prohibited.
> 
> —
> 
> You are receiving this because you modified the open/close state.
> 
> Reply to this email directly, view it on GitHub
> 
> https://github.com/KantaraInitiative/CISWG/issues/54#issuecomment-228565252,
> 
> or mute the thread
> 
> https://github.com/notifications/unsubscribe/ACGyUO2p-Fe8TGDLqBb5DpGTeYh3e8_Pks5qPXtegaJpZM4I-YT9
> 
> .

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.

## 

This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited.
