### ISSUE TITLE
Questions about what Human Readable Means? 

### ISSUE THREAD

**Issue by smartopian** [KantaraInitiative/CISWG#55]
Does Human Readable technically mean - is this the same as - Readable by a Human, Accessible by Human etc ? 

Can we further clarify what human readable means, or list what it refers to?  Does this mean Readable by a Human in English on a website?   Does it mean (or should we include )  W3C Accessibility Guidelines (WCAG 2.0)  used by ISO IEC/40500 (which use to be in  earlier v.6.0 of this spec)? 

Would it (or Should) this definition include the use of Icons?  - i.e - UMA Spec has an icon field - (icon_uri)
"OPTIONAL. A URI for a graphic icon representing the resource set. The authorization server MAY use the referenced icon in any user interface it presents to the resource owner." 

Could the Human Readable (in our definition) be further defined with a scope, created by implementor in the receipt, which uses an icon, and/or links to a 3rd party trust auditing and programs ?  Would/Could  Human Readable then be defined by the 3rd Party Trust Framework? 

Is there a  Human Readable  Use Case as an example ?

**Comment by PrivacyCDN** [comment]
The human readable use case is Alice registering on Bob's web site and getting a receipt that she can read and, optionally, save or print. A web page, pop up or pdf containing the information identified in mode 1 would all meet the requirements. 

Get Outlook for iOS

On Sun, Jun 26, 2016 at 2:42 PM -0400, "Mark Lizar" notifications@github.com wrote:

Does Human Readable technically mean - is this the same as - Readable by a Human, Accessible by Human etc ? 

Can we further clarify what human readable means, or list what it refers to?  Does this mean Readable by a Human in English on a website?   Does it mean (or should we include )  W3C Accessibility Guidelines (WCAG 2.0)  used by ISO IEC/40500 (which use to be in  earlier v.6.0 of this spec)? 

Would it (or Should) this definition include the use of Icons?  - i.e - UMA Spec has an icon field - (icon_uri)

"OPTIONAL. A URI for a graphic icon representing the resource set. The authorization server MAY use the referenced icon in any user interface it presents to the resource owner." 

Could the Human Readable (in our definition) be further defined with a scope, created by implementor in the receipt, which uses an icon, and/or links to a 3rd party trust auditing and programs ?  Would/Could  Human Readable then be defined by the 3rd Party Trust Framework? 

Is there a  Human Readable  Use Case as an example ? 

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.

## 

This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. 
If you have received this email in error please notify the system manager. 
This message contains confidential information and is intended only for the 
individual named. If you are not the named addressee you should not 
disseminate, distribute or copy this e-mail. Please notify the sender 
immediately by e-mail if you have received this e-mail by mistake and 
delete this e-mail from your system. If you are not the intended recipient 
you are notified that disclosing, copying, distributing or taking any 
action in reliance on the contents of this information is strictly 
prohibited.

**Comment by maryhodder** [comment]
Human readable also means:  not legalize where certain terms have a legal
framework or are a legal term of art that isn't apparent to regular humans.

**Comment by smartopian** [comment]
So, we took a vote to call a Conformance mode - Human Readable, which has no reference besides John use for his  Undocumented Use Case.  And that it means not - legalise? 

I think we have a responsibility to a) define it, and b) technically achieve it   - Is this not the purpose of this document?

**Comment by maryhodder** [comment]
I don't think we need a use case for "human readable".. it's well used and
well supported.

> Here is a google search on it, showing it is used, WITHOUT DEFINING, in
> many iso standards:
> https://www.google.com/search?q=standard+human+readable+iso&oq=standard+human+readable+iso&aqs=chrome..69i57.4991j0j7&sourceid=chrome&ie=UTF-8

1.1m results there.. and click into the docs in the first two pages.. they
are ISO standards that talk about "human readable" but none of them include
it in their terms or definitions because it's assumed people know what that
is.

> Here is a wikipedia definition:
> https://en.wikipedia.org/wiki/Human-readable_medium
> "In computing https://en.wikipedia.org/wiki/Computing, _human-readable_ data
> is often encoded as ASCII https://en.wikipedia.org/wiki/ASCII or Unicode
> https://en.wikipedia.org/wiki/Unicode text, rather than presented in a
> binary https://en.wikipedia.org/wiki/Binary_file representation.
> Virtually all data can be parsed by a suitably equipped and programmed
> computer or machine; reasons for choosing binary formats over text formats
> usually center on issues of storage space, as a binary representation
> usually takes up fewer bytes https://en.wikipedia.org/wiki/Byte of
> storage, and efficiency of access (input and output) without parsing
> https://en.wikipedia.org/wiki/Parsing or conversion."
> 
> And Open Data Handbook on Human readable:
> http://opendatahandbook.org/glossary/en/terms/human-readable/
> "Data in a format that can be conveniently read by a human. Some
> human-readable formats, such as PDF
> http://opendatahandbook.org/glossary/en/terms/pdf/, are not
> machine-readable
> http://opendatahandbook.org/glossary/en/terms/machine-readable/ as they
> are not structured data
> http://opendatahandbook.org/glossary/en/terms/structured-data/, i.e. the
> representation of the data on disk does not represent the actual
> relationships present in the data."
> 
> as opposed to Machine Readable:
> http://opendatahandbook.org/glossary/en/terms/machine-readable/
> "Data in a data format that can be automatically read and processed by a
> computer, such as CSV http://opendatahandbook.org/glossary/en/terms/csv/,
> JSON http://opendatahandbook.org/glossary/en/terms/json/, XML
> http://opendatahandbook.org/glossary/en/terms/xml/, etc. Machine-readable
> data must be structured data
> http://opendatahandbook.org/glossary/en/terms/structured-data/. Compare
> human-readable
> http://opendatahandbook.org/glossary/en/terms/human-readable/.

"Non-digital material (for example printed or hand-written documents) is by
its non-digital nature not machine-readable. But even digital material need
not be machine-readable. For example, consider a PDF document containing
tables of data. These are definitely digital but are not machine-readable
because a computer would struggle to access the tabular information - even
though they are very human readable
http://opendatahandbook.org/glossary/en/terms/human-readable/. The
equivalent tables in a format such as a spreadsheet would be machine
readable.

"As another example scans (photographs) of text are not machine-readable
(but are human readable!) but the equivalent text in a format such as a
simple ASCII text file can machine readable and processable.

"Note: The appropriate machine readable format may vary by type of data -
so, for example, machine readable formats for geographic data may differ
from those for tabular data."

> s opposed to Legalese:

http://www.merriam-webster.com/dictionary/legalese

"the language used by lawyers that is difficult for most people to
understand : legal jargon"

**Comment by smartopian** [comment]
Ok,, great -  , I suppose a summary of the above would work with reference to the Kantara Implementation. 

Is A good example?  the Kantara Implementation. 
- where the consent receipt can be seen/captured on the screen.
