### ISSUE TITLE
Revising the CR towards GDPR regulatory approach and data protection principles

### ISSUE THREAD

**Issue by dturnerx** [KantaraInitiative/CISWG#91]
Introductory comments from Jens Kremer - more on attachment provided (a commented v1.0.0 spec): The definition of consent is not in line with the broad understanding of the term in data protection law. Consent is defined as ‘Consent is an individual agreeing to allow an organization to collect, use, and/or disclose their data, and data about them, according to a set of terms and conditions defined by the organization.’ Consent, however, should be ‘…any freely given, specific, informed and unambiguous indication of the data subject's wishes by which he or she, by a statement or by a clear affirmative action, signifies agreement to the processing of personal data relating to him or her;’. This appear to mix consent with contract or agreement. It is important to keep consent and contract separated, because these are entirely different concepts. Surely, one ‘consents’ to signing a contract, but Data Protection law (and especially the GDPR) takes a very different stand. This problem is reflected throughout the paper, and results in a mix up of concepts throughout (see detailed comments).
The terminology in the paper uses ISO standards. Particlularily with the recent push of regulation in Europe, and in global data protection law, it may make sense to adjust the terms to be in line with global data protecton standards (OECD, UN, COE, and especially GDPR).
The document seems to understand ‘consent’ as a transferable and tradeable commodity rather than an expression of a persons will and interest. This is problematic. Beyond consent, other important concepts such as ‘purpose’ may require clarification if not reformulation.
One of the most challenging issues with the specification is that it seems to adopt a very problematic, controller/processor centered approach to consent. Conditions seem to be defined by that entity, and the consent is tracked mainly from that perspective. This is rather problematic as it disregards the role of data subjects. This is certainly not in line with the principles of data protection. Especially not with GDPR.

**Comment by PrivacyCDN** [comment]
WRT, "The document seems to understand ‘consent’ as a transferable and tradeable commodity rather than an expression of a persons will and interest. ". What makes more sense to me is to think of the consent receipt as an artefact, the contents of which can be used as metadata attached to a file or record related to a person such that processing of that data is constrained by the metadata.

**Comment by andrewhughes3000** [comment]
@PrivacyCDN ok so In reading the specification text, Jens came to the understanding that the spec treats consent as a tradeable commodity. Is this what we intended to say? If not, then what did we intend to say in the spec? It's not a matter of what makes sense to us - it's a matter of stating our understanding clearly enough so that others reach the same understanding.

**Comment by PrivacyCDN** [comment]
I don't think we intended to say that consent as a traceable commodity. It's interesting that it can be read that way, and indicates I think that we do need to clarify. I think what we are trying NOT to say what consent is, but rather what information a transactional record of consent being granted (however that happens in the context of the parties to the transaction) should contain to be generally applicable in multiple transactional contexts.

**Comment by smartopian** [comment]
First,  the reference to contract should be removed from the specification and the specification should remain exclusive to privacy policies and personal data from a rights/legal perspective.  (as it is currently defined) 

***
In terms of terminology 

 The objective of this specification is to be able map to an international standard..     Not to proscribe the terminology and definitions used in the receipt itself.  The benefit of using an ISO lexicon is that it is internationalised.  It can also (in the future)  be compatible with the high ISO standards that are used globally.  Just as easily as it can be used to only (or also) comply with the proof of consent as prescribed by the   GDPR notices.  

Although, I personally agree with Jens,  the GDPR is a very strong and sets and enforceable standard that can be mapped to the ISO definitions.  

As an idea for revising toward a more friendly GDPR language specification;    Could we map GDPR and ISO terms in the specification ? (so that some terms can be used interchangeably)

For instance (besides consent) the terms; 
- Personal Data, Data Subject, Data Controller and Data Processor, 
- Personally Information,  Personal Information Principal, Personal Information Controller, and Personal Information Processor.   (they are shorter acronyms as well)

**
Consent as a commodity -to me this is the opposite sort of reaction the receipt should receive from a lawyer (if possible)  There is no  value or benefit framework in the receipt.  

The consent receipt specification is intended to provide a consistent best practice for the common (across jurisdictions) 'legally required' notice information, which needs to be linked to the receipt, for the receipt itself have the capacity of demonstrating compliance with notice requirements. 

The consent receipt (IMO) should be a  specification  that any organisations can use as apart of their consent flow (to capture the notices for collection, use, treatment of personal data) and provide a notice of this to the data subject.

**Comment by smartopian** [comment]
In Re; language - Perhaps in the introduction not refer to a specific definition of consent, but instead refer to how the receipt can be used for consent in multiple jurisdictions.

**Comment by smartopian** [comment]
Thinking about this further..  

There is a deeper issue that is quite significant in the context of the specification. This is between the ISO distinction between personal information and personally identifiable information.  Which effectively means in the ISO standards context there is this mechanism for the use non-personally identifying personal information for a broad categories of uses which only required implied consent and notice. 

In the GDPR the definition is Personal Data, but it is interpreted this way:
**** Recital : (26) The principles of data protection should apply to any information concerning an identified or identifiable natural person. Personal data which have undergone pseudonymisation, which could be attributed to a natural person by the use of additional information should be considered to be information on an identifiable natural person. To determine whether a natural person is identifiable, account should be taken of all the means reasonably likely to be used, such as singling out, either by the controller or by another person to identify the natural person directly or indirectly. To ascertain whether means are reasonably likely to be used to identify the natural person, account should be taken of all objective factors, such as the costs of and the amount of time required for identification, taking into consideration the available technology at the time of the processing and technological developments. The principles of data protection should therefore not apply to anonymous information, namely information which does not relate to an identified or identifiable natural person or to personal data rendered anonymous in such a manner that the data subject is not or no longer identifiable. This Regulation does not therefore concern the processing of such anonymous information, including for statistical or research purposes.
**** 

So _ perhaps: 

If the definition of what is termed identifiable in ISO is matched and compared to what is termed identifiable in the GDPR then the use of the ISO language would be more functionally operational for communicated about non identified and identified personal information ..     Its really the clarity and consensus on the interpretation of this by the identity community which could be significant. 
 
ISO Definition --> 
"any information (a) that can be used to identify the person to whom such information pertains, (b) from which such information can be derived, or (c) that is or might be directly or indirectly linked to a natural person."

Note: I would agree that this work group is not in the business of making definitions , but I do thing that this WG/Kantara is in a unique position to opine on the difference between the two definitions. 

(an aside) That being said I read this last week on a list that if you starve a room full of identity people of  oxygen they will start to argue over definitions.
