### ISSUE TITLE
Purpose Category Contribution

### ISSUE THREAD

**Issue by smartopian** [KantaraInitiative/CISWG#96]
A contribution for '[how to specify a purpose category'](https://docs.google.com/document/d/1z9t2BezbvWa_UmpDruf2PAxKQBssIiPGNEpsLrcBfmM/edit?usp=sharing) is being developed.   

This contribution proposes a taxonomy for the Purpose Category and a list of considerations that are specific to the fields in the consent receipt specification .  It has two sub-issues.

1.  what considerations are needed for specifying a purpose category - this would be a second comment needing more volunteers. 
2. a use case to produce guidelines and example for specifying a purpose category. 

The aim is to develop this contribution through workgroup discussion ([see CR Legal Notes](https://kantarainitiative.org/confluence/pages/viewpage.action?pageId=92307945))  and to provide a draft guide for CR v.1.1 on how to specify a purpose category.  This issue  involves creating an example use case.  (which will be appended to this thread)

**Comment by dturnerx** [comment]
Two issues come to mind after reading the proposal. 

1.  "Core function" will probably be harder than most of the secondary or ancillary purposes. For example, look at the navigation app Waze. It may appear that the only PII it needs is your GPS data. However, one of its route optimization features looks at the **actual** route you took relative to the suggested route. It integrates that information over time and will modify its route suggestions accordingly. This means that Waze is also gathering additional PII relating to routes taken, time of day, and data generated by the **algorithmic** processing of that data. 

2. Simplicity is critical. Remember, whatever information is included in any hierarchy must, at some point, be presented to an end user. Looking at the proposed template,

- Data types (PII Categories) 
- Data Treatment
       - Retention, termination, storage, use, 3rd party uses, recipients, generic policy clauses for the purpose category. 
- Suggested User Terms/Options for industry best practice 
     - What are the opt-ins and out’s - point to marketing example 
- Consent Type - opt in and out, common authorisations, policies and notice for that purpose category (aka UMA scopes)

this is a lot of information to present to an end user. Add a second purpose category and we'll end up back where we are today; users won't pay attention to the notice and will simply click "OK/Accept".

**Comment by smartopian** [comment]
Some good questions here that exposes need for clarity and guidance on this topic.  In particular,  a purpose category is meant to massively simplify layering policy in a human readable manner. 

Purpose Category and sub-category are meant to simplify notice requirements.  Core function as it is I think is an addition field that would be at the purpose category sub-category layer.  (if not selected as a core function, this would then be understood in machine readable form as a secondary purpose) 

For example - Purpose Category=Marketing  - Subcategory=product update 
(this would not have the core function field selected - it would then be a secondary purpose) 

This means if the user de-selects this purpose it will not mean withdrawing consent for the service an core functions. 

The user would most likely see a Purpose category Icon with (x number of purposes on that icon) in a layered policy.  If they click on this icon the user could see how many of the purpose are core to the service and what preferences they have.  under a specific sub-category  there would then by another layers for the detail of that one service. I.e. 

- Data types (PII Categories)
- Data Treatment
- - Retention, termination, storage, use, 3rd party uses, recipients, generic policy clauses for the purpose category.

--> These are different elements which would inform the available preference and best practice - which is why they are considerations for understanding a purpose category (and make the experience more understandable for the User) 
- Suggested User Terms/Options for industry best practice
- Consent Type - opt in and out, common authorisations, policies and notice for that purpose category

**Comment by iainh1** [comment]
I think having a two layered approach might cause as many problems as it solves. A simple, online, machine readable reference multi-select pick-list of purposes with good descriptions would likely be a better option in my view.

Iain

**Comment by smartopian** [comment]
I think we need to distinguish between purpose category and purpose description

These are different things.

**Comment by smartopian** [comment]
Here is a link to the  developing contribution of[ Specifying a purpose categories for marketing](https://docs.google.com/document/d/1nL0m3AkhEa03y9MygcHl733oj59lNKjI-9xzVRKySnE/edit?usp=sharing)

**Comment by PrivacyCDN** [comment]
The more I look at this the more I'm coming to the conclusion that - for the purposes of a receipt - purpose categories may be superfluous to needs but may be a valid profile or extension. Some of the discussion above indicates the utility of purpose categories within a privacy policy. This makes sense but we have a pointer to the policy in the receipt, so is it not overly complicated and/or duplicative to provide the same info in the receipt?

The point above about purpose(s) that are necessary for the core service(s) and those that are not necessary is a good one. The issuance of a receipt would indicate consent for core services but can not imply consent for non-core services. Those consents should be recorded separately to allow revocation and a new receipt.

The receipt is a point in time record that should record the purposes for which personal data was collected. Each use of the data needs to match to a purpose, and each purpose needs to be authorized by the consent - creating the delegation of authority necessary for processing. 

Thus:

> Consent has been given for one or more Purpose(s) each of which authorizes one or more uses of personal data.  

All purpose related to core service can be captured in one line, but each optional consent should be paired with a specific purpose:

Core Consent > Purpose 1 , 2, 3
Optional Consent (opt-in) > Purpose 4
Optional Consent (opt-out) > Purpose 5

**Comment by smartopian** [comment]
-Good point -- this is getting into the how to present the purpose  in a receipt. (human readable) and the structure to work out that presentation.  I think your right this should perhaps be part of guidance for the consent receipt overall and the purpose specification capability  of the receipt for disclosure and sharing.

**Comment by smartopian** [comment]
In terms of layering the purpose specification with un-necessary layers, we could make the purpose category and sub-category field May - or define a consent type i.e. implied consent

**Comment by RupertGravesDIC** [comment]
I have a few points to make. 
1.  I would argue that making standardised purpose categories intelligible to average data subjects is beyond the scope of us all. It comes down to local law (in the case of healthcare, legal services, law enforcement, public safety etc), individual organisations, businesses and codes of conduct of trade associations. To make purpose category definitions intelligible to the average person in the UK, you will need to pitch it at a reading age of a 9-year-old. The most popular media outlets use this level of language intentionally because it works! I am pretty sure the situation would be similar in many other countries.  
2. Being unable to make standardised purpose categories that are intelligble to people with a reading age of 9 does not stop potential benefits coming from validated and standardised purposes. The whole process becomes much easier if this aspect of the challenge is removed.
4. The two main considerations for purpose definition are scope and transparency. These are things that can be tested for normatively (I have done this using ISO29100 data privacy principles).
5. These validated and standardised purposes can link to "_plain language_" explanations for the purposes depending on context and jurisdiction. There is still a benefit to the data subject as standardised purpose limitation is built into the "_plain language_" explanation/defintion.
6. The standardised purposes provide a key part of an audit trail, so a complaints handling process, for example, is much easier to understand and manage for all stakeholders (including data subjects).
7. I agree that although there is a necessity to consider a hierarchy of purposes, it is only relevant in niche cases such as in a health research. In most cases, purposes work in parallel to provide the service.
8. As regards a consent receipt, the consent relates one or more separate purposes that would typically be related to providing a service (context). I propose that both the plain language explanation and the short-code for the technical purpose category are needed here.
9. Marketing is a very wide area and a good one for Consent Receipts. I have identified over 50 purpose categories related to marketing and media via a scope and transparency test. There are so many layered contexts to marketing that the number of useable purposes rapidly expands. However, these can be grouped into 5 main types that have their own contexts. Once in right context explanations are not too tough.

**Comment by dturnerx** [comment]
This is being developed as an external spec.
